set_mode:
  description: Set monitoring mode for a given location
  fields:
    entity_id:
      description: The location monitoring mode entity id to call service on.
      example: 'switch.house_water_mode'
    preset_mode:
      description: Preset mode to switch to (home, away, sleep)
      example: 'away'

run_health_test:
  description: Run the health test on a water control valve.
  fields:
    entity_id:
      description: The valve entity id to call service on.
      example: 'switch.water_valve'