set_preset_mode:
  description: Set preset mode for the water control device.
  fields:
    entity_id:
      description: The valve entity id to call service on.
      example: 'switch.water_valve'
    preset_mode:
      description: Preset mode to switch to (home, away, sleep)
      example: 'away'

run_health_test:
  description: Run the health test on a water control valve.
  fields:
    entity_id:
      description: The valve entity id to call service on.
      example: 'switch.water_valve'